config/routes.rb
Rails.application.routes.draw do
  get 'groups/show'

  get 'users/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top#index"
  resources :users, only: [:show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only: [:create, :show]
  resources :answers, only: [:new, :create, :edit, :update]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  has_one :feed_content, as: :content, dependent: :destroy

  after_create :create_feed_content
  after_update :update_feed_content

  validates_presence_of :user_id, :text

  private

    def create_feed_content
      self.feed_content = FeedContent.create(group_id: question.group_id, updated_at: updated_at)
    end

    def update_feed_content
      self.feed_content.update(updated_at: updated_at)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed_content.rb
class FeedContent < ApplicationRecord
  belongs_to :content, polymorphic: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
  has_many :questions, ->{order("created_at DESC")}
  has_many :feed_contents, -> {order("updated_at DESC")}
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :answers

  has_one :feed_content, as: :content, dependent: :destroy

  validates_presence_of :user_id, :text, :group_id

  after_create :create_feed_content

  def user_answer(user_id)
    Answer.find_by(user_id: user_id, question_id: id)
  end

  def answered?(user)
    self.answers.exists?(user_id: user.id)
  end

  private

    def create_feed_content
      self.feed_content = FeedContent.create(group_id: group_id, updated_at: updated_at)
    end
end

app/models/user.rb
class User < ActiveRecord::Base

  #accessor
  attr_accessor :group_key

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable,
         authentication_keys: [:email, :group_key]

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]


  #association
  belongs_to :group
  has_many :questions, ->{order("created_at DESC")}
  has_many :answers, -> {order("updated_at DESC")}
  has_many :answered_questions, through: :answers, source: :question

  #validation
  before_validation :group_key_to_id, if: :has_group_key?

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    group_key = conditions.delete(:group_key)
    group_id = Group.where(key: group_key).first
    email = conditions.delete(:email)

    # devise認証を、複数項目に対応させる
    if group_id && email
      where(conditions).where(["group_id = :group_id AND email = :email",
        { group_id: group_id, email: email }]).first
    elsif conditions.has_key?(:confirmation_token)
      where(conditions).first
    else
      false
    end
  end

  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end

  def full_profile?
    avatar? && family_name? && first_name? && family_name_kana? && first_name_kana?
  end

  private
  def has_group_key?
    group_key.present?
  end

  def group_key_to_id
    group = Group.where(key: group_key).first_or_create
    self.group_id = group.id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :redirect, only: :new

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @answer.question_id = @question.id
  end

  def create
    @answer = Answer.create(create_params)
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
    @answer = Answer.find(params[:id])
    @question = @answer.question
    @answer.update(update_params)
  end

  private

    def create_params
      params.require(:answer).permit(:question_id, :text).merge(user_id: current_user.id)
    end

    def update_params
      params.require(:answer).permit(:text)
    end

    def redirect
      if Answer.exists?(question_id: params[:project_id], user_id: current_user.id)
        redirect_to :root
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:group_key])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:group_key])
    devise_parameter_sanitizer.permit(:account_update, keys: [:group_key])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(update_params)
  end

  private

    def update_params
      params.require(:group).permit(:key, :detail)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    Question.create(create_params)
    redirect_to :root and return
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  private

    def create_params
      params.require(:question).permit(:text).merge(user_id: current_user.id, group_id: current_user.group_id)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @question = Question.new
    @feed_contents = current_user.group.feed_contents.includes(:content).page(params[:page]).per(5)
    @feed_contents_resource = @feed_contents.map(&:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @questions = @user.answered_questions.uniq
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(update_params)
  end

  private

    def update_params
      params.require(:user).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :avatar)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<div class="answer_content top_content">
  <header class="answer_header">
    <div class="answer_image icon_image" style="background-image: url(<%= answer.user.avatar.url(:medium) %>);"></div>
    <div class="answer_user_info user_info">
      <span><%= link_to answer.user.name, user_path(answer.user) %></span>
      <time><%= time_ago_in_words answer.updated_at %></time>
    </div>
  </header>
  <div class="answer_body">
    <div class="answerd">
      <%= answer.question.user.name %>の質問「<%= link_to answer.question.text, question_path(answer.question) %>」に回答しました。
    </div>
    <% if answer.question.answered?(current_user) %>
      <div class="answer_box">
        <span class="a">A</span>
        <span class="answer_text"><%= answer.text %></span>
        <% if answer.user_id == current_user.id %>
          <small class="edit">
            <%= link_to '編集', edit_answer_path(answer) %>
          </small>
        <% end %>
      </div>
    <% end %>
    <% if answer.question.answers.count > 1 %>
      <div class="answer_other">
        <%= link_to "他#{answer.question.answers.count - 1}件の回答を見る", question_path(answer.question) %>
      </div>
    <% end %>
  </div>
</div>

app/views/answers/create.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>回答の作成が終了しました。</h3>
    <%= link_to "他の人の回答を見る", question_path(@answer.question) %>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>

app/views/answers/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for(@answer) do |f| %>
      <h3><span>Q</span><%= @question.text %></h3>
      <div class="form-group">
      <%= f.text_area :text, placeholder: "回答を入力してください", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
      </div>
      <%= f.submit "回答する", class:"btn btn-primary withripple"%>
    <% end %>
  </div>
</div>

app/views/answers/new.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for(@answer) do |f|%>
      <h3><span>Q</span><%= @question.text %></h3>
      <div class="form-group">
        <%= f.text_area :text, placeholder: "回答を入力してください", cols: "30", rows: "10", autofocus: "true", class: "form-control"%>
      </div>
      <%= f.hidden_field :question_id %>
      <%= f.submit "回答する", class: "btn btn-primary withripple" %>
    <% end %>
  </div>
</div>

app/views/answers/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>質問「<%= @question.text %>」への回答を編集しました</h3>
    <%= link_to "自分の回答を見る", user_path(current_user)%>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>

app/views/common/_header.html.erb
<% if user_signed_in? %>
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to root_path, :class => 'navbar-brand' do %>
        <%= image_tag 'logo.png' %> <small class='hidden-xs hidden-sm'>仲間とプロフィールを共有しよう！</small>
      <% end %>
      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'HOME', root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">グループ<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to current_user.group.key, group_path(current_user.group) %></li>
              </ul>
          </li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アカウント <span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
              <li><%= link_to 'マイページ', user_path(current_user) %></li>
              <li><%= link_to 'プロフィール', edit_user_path(current_user) %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/common/_login_logo.html.erb
<div class="sign_up_logo">
  <%= image_tag 'logo.png' %>
  <small>仲間とプロフィールを共有しよう！</small>
</div>

app/views/groups/edit.html.erb
<% provide :title, "| #{@group.key}" %>
<div class="row form">
  <div class="col-lg-12">
    <%= form_for @group do |f|%>
      <div class="form-group">
          <%= f.label :key, :Name, class: "control-label"%>
          <%= f.text_field :key, placeholder: "グループ名を入力してください", class: "form-control" %>
      </div>

      <div class="form-group">
          <%= f.label :detail, :Detail, class: "control-label"%>
          <%= f.text_field :detail, placeholder: "グループ概要を入力してください", size: "30x10", class: "form-control" %>
      </div>

      <%= f.submit "送信", class: "btn btn-primary withripple"%>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide :title, "| #{@group.key}" %>
<div class="row form">
  <div class="col-lg-12">
    <h3><%= @group.key %>
      <small class="edit">
        <%= link_to "編集", edit_group_path(@group)%>
      </small>
    </h3>
    <p><%= @group.detail.blank? ? "このグループの説明はありません" : @group.detail%></p>
    <div class="group_action panel panel-default"></div>
      <h3>Member List</h3>
    <div class="list-group">
      <% @group.users.each do |user| %>
        <div class="list-group-item"><%= link_to user.name, user_path(user) %><hr></div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>グループの編集が完了しました</h3>
    <%= link_to "一覧へ戻る", group_path(@group)%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Profy<%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <script type='text/javascript' charset='utf-8'>
      $(function(){
        $.material.init();
      });
    </script>
    <%= render partial: 'common/header' %>
    <div class='container'>
      <div class='row'>
        <div class='col-lg-12'>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
      <footer class='row text-center'>
        <p>(C) Profy 2015</p>
      </footer>
    </div>
  </body>
</html>

app/views/questions/_answer.html.erb
<section class="col-md-12">
<div class="sct_inner">
<p><%= link_to answer.user.name, user_path(answer.user) %>さんの回答</p>
<h4>→<%= answer.text %></h4>
</div>
</section>

app/views/questions/_question.html.erb
<div class="question_content top_content">
  <header class="question_header">
    <div class="question_image icon_image" style="background-image: url(<%= question.user.avatar.url(:medium) %>);"></div>
    <div class="question_user_info user_info">
    <span><%= link_to question.user.name, user_path(question.user) %></span>
    <time><%= time_ago_in_words question.created_at %></time>
    </div>
  </header>
  <div class="question_body">
    <div class="question_box">
      <span class="q">Q</span>
      <span class="question_text"><%= question.text %></span>
    </div>

    <div class="questioned">
      <%= link_to "回答#{question.answers.count}件", question_path(question) %>
    </div>

    <% unless question.answers.exists?(user_id: current_user.id) %>

      <%= form_tag(new_answer_path, method: :get, class: "question_submit") do %>
        <%= hidden_field_tag(:question_id, question.id) %>
        <%= submit_tag("回答する")%>
      <% end %>

    <% else %>
      <div class="answer_other">
        <h4>＊回答済み＊</h4>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3><span>Q</span><%= @question.text %></h3>
      <div class="group_action panel panel-default">
        <div class="panel-body">
          <% unless @question.answers.exists?(user_id: current_user.id) %>
          <%= link_to '質問に回答する', new_answer_path(question_id: @question.id) %>
          <% else %>
          <h4>※回答済み※</h4>
          <% end %>
        </div>
      </div>
    <% if @question.answers.present? %>
      <h3><span>A</span>この質問への回答</h3>
      <% if @question.answered?(current_user) %>
        <%= render partial: "questions/answer", collection: @answers %>
      <% else %>
        <h1>＊質問に応えると他の人の回答を見ることができます＊</h1>
      <% end %>
    <% end %>
  </div>
</div>

app/views/top/index.html.erb
<% unless current_user.full_profile? %>
  <header class="header_top panel panel-default col-lg-12 no-profile">
    <h2>まずは、あなたの基本プロフィールを登録しましょう！</h2>
    <p>Profyは友達の質問に答えながらプロフィールを作るサービスです！</p>
    <%= link_to "プロフィールを登録する", edit_user_path(current_user), {class: "btn btn-lg btn-primary withripple"}%>
  </header>
<% else %>
  <div class="posting_form top_content">
    <header class="posting_header">
      <div class="posting_image icon_image" style="background-image: url(<%= current_user.avatar.url(:medium) %>);"></div>
      <div class="posting_user_info user_info">
      <%= current_user.name %>
      </div>
    </header>
    <%= form_for(@question) do |f| %>
      <%= f.text_field :text, placeholder: "例：好きな食べ物は？" %>
      <%= f.submit "質問する" %>
    <% end %>
  </div>

  <%= render @feed_contents_resource %>

  <%= paginate(@feed_contents)%>

<% end %>

app/views/users/_question.html.erb
<div class="question_content top_content">
  <div class="question_body">
    <div class="question_box">
      <span class="q">Q</span>
      <span class="question_text"><%= question.text %></span>
    </div>
    <div class="answer_box" style="margin-bottom: 10px;">
      <span class="a">A</span>
      <span class="answer_text"><%= question.user_answer(@user.id).text %></span>
      <% if @user.id == current_user.id %>
        <%= link_to "編集", edit_answer_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide :title, "| #{@user.name}さん" %>
<div class="row form">
  <div class="col-lg-12">
    <%= form_for current_user do |f| %>
      <h2>プロフィール画像</h2>
      <div class="form-group file">
        <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <h2>登録情報</h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name, placeholder: "性", class: "form-control"%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :first_name, placeholder: "名", class: "form-control"%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name_kana, placeholder: "セイ", class: "form-control"%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :first_name_kana, placeholder: "メイ", class: "form-control"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple"%>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, "| #{@user.name}さん" %>
<div class="row form user_profile">
  <div class="col-lg-12">
    <div class="image" style="background-image: url(<%= @user.avatar.url(:medium) %>);"></div>
    <h2><%= @user.name%><span><%= @user.name_kana %></span></h2>
    <% if current_user.id == @user.id %>
      <div class="profile-edit">
        <%= link_to 'プロフィール編集', edit_user_path(current_user), {:class => "btn btn-primary withripple"}%>
      </div>
    <% end %>
    <% if @questions.present? %>
      <div class="clearfix">
        <%= render partial: 'users/question', collection: @questions%>
      </div>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>